### ISSUE TITLE
[1.19.2][Forge] Ticking Entity Crash

### ISSUE THREAD

**Issue by ffuentesm** [Jarva/Ars-Artifice#1]
Ars Artifice: 1.0.1
Ars Nouveau:3.13.2
Forge: 43.2.8

The game crashed to game menu after I tried to fight a few Zombies. 

Here is the crash report
https://pastebin.com/0aCp7raP

**Comment by Jarva** [comment]
This should now be fixed in [1.0.2](https://github.com/Jarva/Ars-Artifice/releases/tag/1.0.2)
