### ISSUE TITLE
Incompatibility with Too Many Glyphs

### ISSUE THREAD

**Issue by RemiRhel** [Jarva/Ars-Artifice#2]
when you've learned enough Glyphs to get a second page in your spellbook, the arrow icon to turn pages also shows up in the Artifice table, clicking it will cause a crash

1.19.2 Forge, Valhelsia 5 Modpack with only these 2 extra mods installed

**Comment by Jarva** [comment]
I'll investigate a fix once I'm back from vacation in a few weeks, until then I can only recommend not pressing the next page button, hopefully the default augments are available on the first page because they're the only ones compatible

**Comment by RemiRhel** [comment]
Oh yeah enjoy your vacation! I just wanted to let you know in case nobody
had found the issue yet.

**Comment by Jarva** [comment]
This should be fixed in v1.0.6

https://modrinth.com/mod/ars-artifice/version/1.0.6
https://legacy.curseforge.com/minecraft/mc-mods/ars-artifice/files/4654344 (under review at time of posting)
